create table employees
(
    id              bigint generated by default as identity,
    contract_type   bigint,
    date_of_ingress date,
    name            varchar(50),
    salary          numeric(19, 2),
    primary key (id)
);

create table contract_types
(
    contract_type_id bigint generated by default as identity,
    type             varchar(50),
    primary key (contract_type_id)
);

create table payments
(
    id                 bigint generated by default as identity,
    employee_id        bigint,
    date_of_payment    date,
    payment_value      numeric(19, 2),
    leave_days         integer,
    medical_disability integer,
    primary key (id)
);


alter table employees
    add constraint fk_employees_contract_type foreign key (contract_type) references contract_types;

alter table payments
    add constraint fk_payments_employee foreign key (employee_id) references employees;


------------------------------------ Contract types Insert -------------------------------

insert into contract_types(type)
values ('FULL');

insert into contract_types(type)
values ('PARTIAL');

------------------------------------ Employees Insert ------------------------------------

insert into employees(contract_type, date_of_ingress, name, salary)
values (1, '2022-05-09', 'User One', 10000000);

insert into employees(contract_type, date_of_ingress, name, salary)
values (2, '2022-04-20', 'User Two', 20000000);

insert into employees(contract_type, date_of_ingress, name, salary)
values (1, '2022-04-21', 'User Three', 20000000);


------------------------------------ Payments Insert ------------------------------------

insert into payments(id, date_of_payment, payment_value, leave_days, medical_disability)
values (1, '2022-05-21', 10000000, 0, 0);