create table employees
(
    id              bigint generated by default as identity,
    contract_type   bigint,
    date_of_ingress date,
    name            varchar(50),
    salary          numeric(19, 2),
    primary key (id)
);

create table contract_types
(
    id   bigint generated by default as identity,
    type varchar(50),
    primary key (id)
);

alter table employees add constraint fk_employees_contract_type foreign key (contract_type) references contract_types;


insert into contract_types(type) values('FULL');
insert into contract_types(type) values('PARTIAL');

insert into employees(contract_type, date_of_ingress, name, salary) values(1, '2022-05-09', 'User One', 20000000);
insert into employees(contract_type, date_of_ingress, name, salary) values(1, '2022-04-20', 'User Two', 20000000);
insert into employees(contract_type, date_of_ingress, name, salary) values(1, '2022-04-21', 'User Three', 20000000);